---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: rhel6.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '6'

- include_tasks: rhel7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '7'

- name: NTP pnd tzdata packages installation
  yum:
    name: "{{ ntp_packages }}"
    state: latest

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"
  notify: restart crond

- name: NTP is running and enabled
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
