---
- name: Remove chrony client package
  yum:
    name: chrony
    state: absent
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Ensure NTP pnd tzdata packages are installed.
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ntp_packages }}"

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"
  notify: restart crond

- name: Ensure NTP is running and enabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
